### ISSUE TITLE
Make all response ResponseEntitty with accept and produce headers

### ISSUE THREAD

**Issue by bhuvancom** [soumyaghosh71/Blogger#1]

**Comment by soumyaghosh71** [comment]
Added 47686f125cffe2ea9c1ed3823481691f50527e02. Please check Sir.
![image](https://github.com/soumyaghosh71/Blogger/assets/126461518/f97ece5a-3c4c-4cac-895e-eecb5fc320ce)

**Comment by bhuvancom** [comment]
LGTM
